### ISSUE TITLE
NoClassDefFoundError for NestableRuntimeException (commons-lang)

### ISSUE THREAD

**Issue by shankhanildas** [dustinschultz/scf-discovery-server#1]
I am getting the below Exception when building the project. common-lang-2.6 is in transitive dependency; it keeps on complaining about NoClassDefFoundError though and not a ClassNotFoundException. 

This is happening for -
 - spring-cloud.version Camden.SR7
 - spring-cloud.version Dalston.x

Camden.SR2 (as committed to this repo) seems to be working  fine.

```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.cloud.netflix.archaius.ArchaiusAutoConfiguration': Unsatisfied dependency expressed through field 'externalConfigurations'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'configurableEnvironmentConfiguration' defined in class path resource [org/springframework/cloud/netflix/archaius/ArchaiusAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.netflix.archaius.ConfigurableEnvironmentConfiguration]: Circular reference involving containing bean 'org.springframework.cloud.netflix.archaius.ArchaiusAutoConfiguration' - consider declaring the factory method as static for independence from its containing instance. Factory method 'configurableEnvironmentConfiguration' threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/commons/lang/exception/NestableRuntimeException
```

**Comment by dustinschultz** [comment]
@shankhanildas thanks for the report. Investigating.

**Comment by dustinschultz** [comment]
@shankhanildas I cloned the repo and changed the version to `Camden.SR7` as well as `Dalston.SR1` and both of the projects built with no errors.

Can you please share your project?

**Comment by shankhanildas** [comment]
@dustinschultz I believe I had a snapshot version of commons-lang:2.6 (had a force update including snapshot earlier) which was causing the conflict and was resulting in NoClassDefError. Cleaning the local repository solved it. Thanks for looking into it.
